### ISSUE TITLE
Does Not Print With Page Numbers

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute-printers-pdf#4]
# User Test for March 18, 2022 | 4:00 p.m. to 5:00 p.m.

After installing ```crosscompute-printers-pdf```, we used the Randomized Histogram project to test printing with page numbers.

### Actual Behavior: Did not print any page number.

Print configuration used:
```yml
# print configuration
  print:
    configuration:
      header-footer:
        font-family: sans-serif
        font-size: 8pt
        color: '#808080'
        padding: 0.1in 0.25in
        skip-first: true
      page-number:
        location: footer
        alignment: right
```

Styling that was used:
```css
body {
  font-family: sans-serif;
  font-size: 12pt;
}

@page {
    margin: 1in;
}
```
